application: bongapp
version: dev
runtime: python
api_version: 1



error_handlers:
- error_code: over_quota
  file: errors/quota.html

- error_code: dos_api_denial
  file: errors/dos.html

- error_code: timeout
  file: errors/timeout.html

#- file: errors/default.html



handlers:

#static files
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /javascript
  static_dir: static/javascript

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.png

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt


#public controllers
- url: /
  script: controllers/dashboard.py

- url: /bulka
  script: controllers/bulka.py


#ois.artun.ee login/out
- url: /logi_bonga(.*)
  script: controllers/logi_bonga.py
  login: required


#protected controllers
- url: /search(.*)
  script: controllers/search.py
  login: required

- url: /person(.*)
  script: controllers/person.py
  login: required

- url: /curriculum(.*)
  script: controllers/curriculum.py
  login: required

- url: /dictionary(.*)
  script: controllers/dictionary.py
  login: required

- url: /delete(.*)
  script: controllers/delete.py
  login: required

- url: /update(.*)
  script: controllers/update.py
  login: required