from database.import.zoin import *
from database.import.dictionary import *
from database.import.general import *
from database.import.person import *
from database.import.grade import *
from database.import.curriculum import *
from database.import.application import *
from database.import.feedback import *
from database.import.oldauth import *
from database.import.aggregation import *